#Create numpy array from numpy function


arrays with zeros

In [10]:
import numpy as np
ar_zero = np.zeros(5)  #array with one dimension

# array with multiple dimension
ar_zero1 = np.zeros((3,4))
print(ar_zero1)
print(ar_zero1.ndim)
print()
print(ar_zero)
print(ar_zero.ndim)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2

[0. 0. 0. 0. 0.]
1


arrays with ones


In [11]:
ar_one = np.ones(4)
print(ar_one)
print()
print(ar_one.ndim)

[1. 1. 1. 1.]

1


empty array

In [12]:
ar_emp = np.empty(5)
print(ar_emp)


[0. 0. 0. 0. 0.]


range

In [13]:
ar_sattar =np.arange(4)
print(ar_sattar)

[0 1 2 3]


Diagnal

In [14]:
ar_dia = np.eye(3)
print(ar_dia)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


linspace


In [15]:
ar_lin =np.linspace(0,10 ,num = 5)
print(ar_lin)

[ 0.   2.5  5.   7.5 10. ]
