create numpy  array with random number


random number


In [1]:
import numpy as np
x =np.random.rand(4)
print(x)

[0.91574732 0.22679349 0.94801192 0.0257542 ]


In [2]:
x=np.random.rand(2,3)
print(x)

[[0.85000367 0.06267954 0.46293611]
 [0.01452234 0.34905393 0.0232763 ]]


In [3]:
x=np.random.randn(4)
print(x)

[-0.53949941 -0.98661145  1.12963434  0.37104128]


In [8]:
x=np.random.ranf(4)
print(x)

[0.84841644 0.89069188 0.75281011 0.10600219]


In [9]:
# x=np.random.randint(min,max,total)
x=np.random.randint(4,20,5)
print(x)

[12  7 15 11  5]
