In [ ]:
#Numpy Arrays
import numpy as np
x=[1,2,3,4,5,6]

y=np.array(x)
print(y)
print(y.ndim)67

[1 2 3 4 5 6]
1


In [6]:
l = []

for i in range(1,5):
    x= int(input("Enter the number"))
    l.append(x)
    print(np.array(l))


[12]
[12 23]
[12 23 45]
[12 23 45 56]


In [14]:
import numpy as np
ar2= np.array([[1,2,3,4,5,6],[5,6,7,8,4,3]])
print(ar2)
print(ar2.ndim)



[[1 2 3 4 5 6]
 [5 6 7 8 4 3]]
2


In [15]:
ar3=np.array([[[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]]
3


In [17]:
arn=np.array([1,2,3,4,5,65,6], ndmin=10)
print(arn)
print(arn.ndim)

[[[[[[[[[[ 1  2  3  4  5 65  6]]]]]]]]]]
10
